### ISSUE TITLE
Never seems to become active

### ISSUE THREAD

**Issue by linuxgurugamer** [AlexanderDzhoganov/CKAN-plugins#5]
I installed the part manager using the "Add new" button on the CKAN Plugins page.  Then I hit the Activate button.

Something happened, but I have no idea what.  It starts showing a tab which says "Installed mods that contain parts", but nothing was listed.

I then tried to unload it, but the tab remained.  It even remained after I restarted.  I had to find where the dll was copied to (the Plugins directory) and delete it manually.

I'm not sure if this is a PartManager issue or a CKAN issue, I'm going to post this in the CKAN issues as well.

**Comment by lumine** [comment]
I have the same issue.  Part Manager 1.2 CKAN 1.16.0

**Comment by Thomdare** [comment]
I believe that after CKAN's registry system change this plugin stopped working
